---
inlets:
  1:
    name: camera
    type: baumer_camera_neoapi
    hidden: False
    parameters:
      device_id: 0
      ExposureTime: 5000
  2:
    name: light_conditions
    type: static_variable
    hidden: False
    parameters:
      value: natural
    metadata:
      unit: none
      interpretation: no artificial light switched on
      description: light conditions during experiment

processors:
  0:
    name: image_input
    type: input
    input_inlets:
      - camera
  1:
    name: image_resize
    type: image_resize
    hidden: true
    parameters:
      width: 248
      height: 248
  2:
    name: classifier
    type: pt_inference
    parameters:
      path_to_models: '../models'
      model_name: 'cats_vs_dogs_pt'
      model_version: '1.0'
shell:
  type: rest_api
  parameters:
    host: 0.0.0.0
    port: 5000
    endpoint: '/get_frame'